[package]
name = "gnss-sdr-rc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.144"
plotpy = "0.3.5"
spectrum-analyzer = "1.4.0"
ringbuffer = "0.14.0"
rustfft = "6.1.0"
realfft = "3.3.0"

[build-dependencies]
bindgen = "0.66.0"
